### ISSUE TITLE
OS dependent commands?

### ISSUE THREAD

**Issue by berry-langerak** [rtuin/pla#6]
Hi! As discussed on Friday, it would be extremely helpful to commit a Plafile to the repository in which you use it, so that you can effectively replace your entire readme file with "pip install pla; pla init" (which is bloody nice, kudos again!).

However, if there is someone using a different OS, the commands I've written might not work (think Debian vs CentOS). I guess it would be nice if you could "tag" commands based on OS type, so that you could run only the commands which actually work on your machine. I'm thinking of a certain syntax like:

``` yaml
restart:
  - (/debian|ubuntu/) sudo service apache2 restart
  - (/centos|rhel/) sudo service httpd restart
```

That might, for example do a `lsb_release -a | grep -Pi "($1)"` on linux, where $1 is the regex in the parentheses in front of the command.

Or perhaps there's a better solution, but I guess this would be a nice addition. :)

**Comment by rtuin** [comment]
Great suggestion @berry-langerak! I've just implemented this on `master`: https://github.com/rtuin/pla#command-os-filter

I've tried to keep it simple. What do you think?
You can try it out by [installing Pla master](https://github.com/rtuin/pla#install-from-git) from git.

**Comment by berry-langerak** [comment]
Freaking awesome! I'll install it today and build a Plafile for the Simpel project. Thanks for the effort dude!
